version: "3.2"

services:
  charges-api:
    image: charges-api
    build:
      context: ChargesApi/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      # - CONNECTION_STRING=Host=dev-database;Port=5432;Database=testdb;Username=postgres;Password=mypassword
# TODO: If using DynamoDb remove the line above and uncomment the section below.
       - DynamoDb_LocalMode=true
       - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
       - AWS_REGION=eu-west-2
       - AWS_ACCESS_KEY_ID=fco1i2
       - AWS_SECRET_ACCESS_KEY=8kmm3g
    links:
      - dev-database
  dev-database:
    env_file:
      - database.env
    image: postgres:12
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  charges-api-test:
    image: charges-api-test
    build:
      context: .
      dockerfile: ChargesApi.Tests/Dockerfile
    environment:
      - DynamoDb_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=fco1i2
      - AWS_SECRET_ACCESS_KEY=8kmm3g
    links:
      - dynamodb-database

  #test-database:
  #  image: test-database
  #  build:
  #    context: .
  #    dockerfile: database/Dockerfile
  #  ports:
  #    - 5432:5432
  #  env_file:
  #    - database.env

# TODO: If using DynamoDb remove the 'test-database' seciton above and uncomment the lines below.
  dynamodb-database:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
